# Generated by Django 2.0.1 on 2023-06-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('numero', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('receptor_visto', models.CharField(max_length=2)),
                ('receptor_nom', models.CharField(max_length=300)),
                ('receptor_ruc', models.CharField(max_length=20)),
                ('emisor_visto', models.CharField(max_length=2)),
                ('emisor_nom', models.CharField(max_length=300)),
                ('emisor_ruc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visita_fecha', models.CharField(max_length=30)),
                ('visita_ip', models.CharField(max_length=300)),
                ('fuente', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor_id', models.CharField(max_length=30)),
                ('receptor_nom', models.CharField(max_length=300)),
                ('receptor_clave', models.CharField(max_length=50)),
                ('receptor_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
